//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Web;
using ServiceStack.WebHost.Endpoints;
using Funq;
namespace mrroad.recommendations.api
{
	public class Global : System.Web.HttpApplication
	{
    

	    //Initialize your application singleton
	    protected void Application_Start(object sender, EventArgs e)
	    {
	        new AppHost().Init();
	    }
	}

}

